name: Feature request
description: "Suggest an idea for this project"
title: "[Feature Request]"
labels: ["enhancement"]
body:
  - type: checkboxes
    id: confirm
    attributes:
      label: Confirm
      description: Please confirm
      options:
        - label: I have searched the Issue and found no related feature requests
          required: true
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you want
    validations:
      required: true
  - type: textarea
    id: how_to
    attributes:
      label: How to Implement
      description: How to implement this feature
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Information
      description: Any other information you think might be helpful to implement this feature
    validations:
      required: false